// <auto-generated />
namespace Software2_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class adding_DataAnnotation_to_Course_Attribute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_DataAnnotation_to_Course_Attribute));
        
        string IMigrationMetadata.Id
        {
            get { return "202004082044052_adding_DataAnnotation_to_Course_Attribute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
