// <auto-generated />
namespace Software2_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changing_Grade_Data_Type_To_float : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changing_Grade_Data_Type_To_float));
        
        string IMigrationMetadata.Id
        {
            get { return "202004220304241_changing_Grade_Data_Type_To_float"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
