// <auto-generated />
namespace Software2_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changing_some_attributes_data_types_in_course_professor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changing_some_attributes_data_types_in_course_professor));
        
        string IMigrationMetadata.Id
        {
            get { return "202004101832423_changing_some_attributes_data_types_in_course_professor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
